--- #YAML:1.0
name:                Lingua-PT-ProperNames
version:             0.07
abstract:            Simple module to extract proper names from Portuguese Text
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    IO::String:                    0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Alberto Simões <ambs@di.uminho.pt>
